package cl.usach.tingeso.service;

import cl.usach.tingeso.dto.StudentRegistrationDTO;
import cl.usach.tingeso.dto.StudentResponseDTO;
import cl.usach.tingeso.dto.StudentUpdateDTO;
import cl.usach.tingeso.entity.AcademicStatus;
import cl.usach.tingeso.entity.CareerEntity;
import cl.usach.tingeso.entity.StudentEntity;
import cl.usach.tingeso.entity.StudyPlanEntity;
import cl.usach.tingeso.exception.BusinessRuleException;
import cl.usach.tingeso.exception.ResourceNotFoundException;
import cl.usach.tingeso.repository.CareerRepository;
import cl.usach.tingeso.repository.StudentRepository;
import cl.usach.tingeso.repository.StudyPlanRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Unit tests for StudentService.
 * Layer: Service.
 * Verifies all business rules and ensures >= 90% code coverage.
 */
@ExtendWith(MockitoExtension.class)
class StudentServiceTest {

    @Mock
    private StudentRepository studentRepository;

    @Mock
    private CareerRepository careerRepository;

    @Mock
    private StudyPlanRepository studyPlanRepository;

    @Mock
    private KeycloakUserService keycloakUserService;

    @InjectMocks
    private StudentService studentService;

    private CareerEntity careerActive;
    private CareerEntity careerInactive;
    private StudyPlanEntity activeStudyPlan;
    private StudentEntity sampleStudent;

    @BeforeEach
    void setUp() {
        careerActive = CareerEntity.builder()
                .code("10450")
                .name("Técnico Analista Programador")
                .description("Formación de técnicos de software.")
                .durationSemesters(4)
                .isActive(true)
                .build();

        careerInactive = CareerEntity.builder()
                .code("99999")
                .name("Carrera Inactiva")
                .description("Carrera cerrada.")
                .durationSemesters(4)
                .isActive(false)
                .build();

        activeStudyPlan = StudyPlanEntity.builder()
                .id(1L)
                .code("2021.3")
                .isActive(true)
                .career(careerActive)
                .build();

        sampleStudent = StudentEntity.builder()
                .run("12345678-5")
                .firstName("Juan Carlos")
                .paternalLastName("Perez")
                .maternalLastName("Gonzalez")
                .email("juan.perez@sigaipt.cl")
                .academicStatus(AcademicStatus.REGULAR)
                .career(careerActive)
                .studyPlan(activeStudyPlan)
                .build();
    }

    // =========================================================================
    // 1. registerStudent Tests
    // =========================================================================

    @Test
    @DisplayName("Should successfully register a student with autogenerated email and active plan")
    void testRegisterStudent_Success() {
        StudentRegistrationDTO dto = StudentRegistrationDTO.builder()
                .run("12345678-5")
                .firstName("Juan Carlos")
                .paternalLastName("Perez")
                .maternalLastName("Gonzalez")
                .careerCode("10450")
                .build();

        when(studentRepository.existsByRun("12345678-5")).thenReturn(false);
        when(careerRepository.findByCode("10450")).thenReturn(Optional.of(careerActive));
        when(studyPlanRepository.findByCareer_CodeAndIsActiveTrue("10450")).thenReturn(Optional.of(activeStudyPlan));
        when(studentRepository.existsByEmail("juan.perez@sigaipt.cl")).thenReturn(false);
        when(studentRepository.save(any(StudentEntity.class))).thenAnswer(invocation -> invocation.getArgument(0));

        StudentResponseDTO response = studentService.registerStudent(dto);

        assertNotNull(response);
        assertEquals("12345678-5", response.getRun());
        assertEquals("juan.perez@sigaipt.cl", response.getEmail());
        assertEquals(AcademicStatus.REGULAR, response.getAcademicStatus());
        assertEquals("Juan Carlos Perez Gonzalez", response.getFullName());
        assertEquals("10450", response.getCareerCode());
        assertEquals("2021.3", response.getStudyPlanCode());
        verify(studentRepository).save(any(StudentEntity.class));
    }

    @Test
    @DisplayName("Should throw BusinessRuleException when RUN has invalid check digit")
    void testRegisterStudent_InvalidRun() {
        StudentRegistrationDTO dto = StudentRegistrationDTO.builder()
                .run("12345678-9") // Invalid check digit (should be 5)
                .firstName("Juan")
                .paternalLastName("Perez")
                .maternalLastName("Gonzalez")
                .careerCode("10450")
                .build();

        BusinessRuleException ex = assertThrows(BusinessRuleException.class, () ->
                studentService.registerStudent(dto));

        assertTrue(ex.getMessage().contains("invalid"));
        verify(studentRepository, never()).save(any());
    }

    @Test
    @DisplayName("Should throw BusinessRuleException when RUN already exists")
    void testRegisterStudent_DuplicateRun() {
        StudentRegistrationDTO dto = StudentRegistrationDTO.builder()
                .run("12345678-5")
                .firstName("Juan")
                .paternalLastName("Perez")
                .maternalLastName("Gonzalez")
                .careerCode("10450")
                .build();

        when(studentRepository.existsByRun("12345678-5")).thenReturn(true);

        BusinessRuleException ex = assertThrows(BusinessRuleException.class, () ->
                studentService.registerStudent(dto));

        assertTrue(ex.getMessage().contains("already registered"));
        verify(studentRepository, never()).save(any());
    }

    @Test
    @DisplayName("Should throw ResourceNotFoundException when career does not exist")
    void testRegisterStudent_CareerNotFound() {
        StudentRegistrationDTO dto = StudentRegistrationDTO.builder()
                .run("12345678-5")
                .firstName("Juan")
                .paternalLastName("Perez")
                .maternalLastName("Gonzalez")
                .careerCode("99999")
                .build();

        when(studentRepository.existsByRun("12345678-5")).thenReturn(false);
        when(careerRepository.findByCode("99999")).thenReturn(Optional.empty());

        assertThrows(ResourceNotFoundException.class, () ->
                studentService.registerStudent(dto));
        verify(studentRepository, never()).save(any());
    }

    @Test
    @DisplayName("Should throw BusinessRuleException when career is INACTIVE")
    void testRegisterStudent_CareerInactive() {
        StudentRegistrationDTO dto = StudentRegistrationDTO.builder()
                .run("12345678-5")
                .firstName("Juan")
                .paternalLastName("Perez")
                .maternalLastName("Gonzalez")
                .careerCode("99999")
                .build();

        when(studentRepository.existsByRun("12345678-5")).thenReturn(false);
        when(careerRepository.findByCode("99999")).thenReturn(Optional.of(careerInactive));

        BusinessRuleException ex = assertThrows(BusinessRuleException.class, () ->
                studentService.registerStudent(dto));

        assertTrue(ex.getMessage().contains("INACTIVE"));
        verify(studentRepository, never()).save(any());
    }

    @Test
    @DisplayName("Should throw BusinessRuleException when career has no active study plan")
    void testRegisterStudent_NoActiveStudyPlan() {
        StudentRegistrationDTO dto = StudentRegistrationDTO.builder()
                .run("12345678-5")
                .firstName("Juan")
                .paternalLastName("Perez")
                .maternalLastName("Gonzalez")
                .careerCode("10450")
                .build();

        when(studentRepository.existsByRun("12345678-5")).thenReturn(false);
        when(careerRepository.findByCode("10450")).thenReturn(Optional.of(careerActive));
        when(studyPlanRepository.findByCareer_CodeAndIsActiveTrue("10450")).thenReturn(Optional.empty());

        assertThrows(BusinessRuleException.class, () ->
                studentService.registerStudent(dto));
        verify(studentRepository, never()).save(any());
    }

    // =========================================================================
    // 2. Query Tests
    // =========================================================================

    @Test
    @DisplayName("Should return all students")
    void testGetAllStudents() {
        when(studentRepository.findAll()).thenReturn(List.of(sampleStudent));

        List<StudentResponseDTO> result = studentService.getAllStudents();

        assertEquals(1, result.size());
        assertEquals("12345678-5", result.get(0).getRun());
    }

    @Test
    @DisplayName("Should return student by RUN when found")
    void testGetStudentByRun_Success() {
        when(studentRepository.findByRun("12345678-5")).thenReturn(Optional.of(sampleStudent));

        StudentResponseDTO result = studentService.getStudentByRun("12.345.678-5");

        assertNotNull(result);
        assertEquals("12345678-5", result.getRun());
        assertEquals("Juan Carlos Perez Gonzalez", result.getFullName());
    }

    @Test
    @DisplayName("Should throw ResourceNotFoundException when student not found by RUN")
    void testGetStudentByRun_NotFound() {
        when(studentRepository.findByRun("12345678-5")).thenReturn(Optional.empty());

        assertThrows(ResourceNotFoundException.class, () ->
                studentService.getStudentByRun("12345678-5"));
    }

    // =========================================================================
    // 3. updateStudent Tests
    // =========================================================================

    @Test
    @DisplayName("Should successfully update student names and allowed academic status")
    void testUpdateStudent_Success() {
        StudentUpdateDTO dto = StudentUpdateDTO.builder()
                .firstName("Juan Pablo")
                .paternalLastName("Perez")
                .maternalLastName("Soto")
                .academicStatus(AcademicStatus.POSTERGACION)
                .build();

        when(studentRepository.findByRun("12345678-5")).thenReturn(Optional.of(sampleStudent));
        when(studentRepository.save(any(StudentEntity.class))).thenAnswer(invocation -> invocation.getArgument(0));

        StudentResponseDTO updated = studentService.updateStudent("12345678-5", dto);

        assertEquals("Juan Pablo", updated.getFirstName());
        assertEquals("Soto", updated.getMaternalLastName());
        assertEquals(AcademicStatus.POSTERGACION, updated.getAcademicStatus());
    }

    @Test
    @DisplayName("Should throw BusinessRuleException when attempting to manually assign EGRESADO")
    void testUpdateStudent_CannotManuallyAssignEgresado() {
        StudentUpdateDTO dto = StudentUpdateDTO.builder()
                .academicStatus(AcademicStatus.EGRESADO)
                .build();

        when(studentRepository.findByRun("12345678-5")).thenReturn(Optional.of(sampleStudent));

        BusinessRuleException ex = assertThrows(BusinessRuleException.class, () ->
                studentService.updateStudent("12345678-5", dto));

        assertTrue(ex.getMessage().contains("EGRESADO and ELIMINADO cannot be assigned manually"));
    }

    @Test
    @DisplayName("Should throw BusinessRuleException when attempting to manually assign ELIMINADO")
    void testUpdateStudent_CannotManuallyAssignEliminado() {
        StudentUpdateDTO dto = StudentUpdateDTO.builder()
                .academicStatus(AcademicStatus.ELIMINADO)
                .build();

        when(studentRepository.findByRun("12345678-5")).thenReturn(Optional.of(sampleStudent));

        BusinessRuleException ex = assertThrows(BusinessRuleException.class, () ->
                studentService.updateStudent("12345678-5", dto));

        assertTrue(ex.getMessage().contains("EGRESADO and ELIMINADO cannot be assigned manually"));
    }

    @Test
    @DisplayName("Should successfully update career when student has no enrollments or history")
    void testUpdateStudent_CareerUpdate_Success() {
        CareerEntity newCareer = CareerEntity.builder()
                .code("10451")
                .name("Técnico en Análisis de Datos")
                .isActive(true)
                .build();

        StudyPlanEntity newPlan = StudyPlanEntity.builder()
                .id(2L)
                .code("2022.3")
                .isActive(true)
                .career(newCareer)
                .build();

        StudentUpdateDTO dto = StudentUpdateDTO.builder()
                .careerCode("10451")
                .build();

        when(studentRepository.findByRun("12345678-5")).thenReturn(Optional.of(sampleStudent));
        when(careerRepository.findByCode("10451")).thenReturn(Optional.of(newCareer));
        when(studyPlanRepository.findByCareer_CodeAndIsActiveTrue("10451")).thenReturn(Optional.of(newPlan));
        when(studentRepository.save(any(StudentEntity.class))).thenAnswer(invocation -> invocation.getArgument(0));

        StudentResponseDTO updated = studentService.updateStudent("12345678-5", dto);

        assertEquals("10451", updated.getCareerCode());
        assertEquals("2022.3", updated.getStudyPlanCode());
    }

    @Test
    @DisplayName("Should throw ResourceNotFoundException when updating career to non-existent career")
    void testUpdateStudent_CareerUpdate_NotFound() {
        StudentUpdateDTO dto = StudentUpdateDTO.builder()
                .careerCode("99999")
                .build();

        when(studentRepository.findByRun("12345678-5")).thenReturn(Optional.of(sampleStudent));
        when(careerRepository.findByCode("99999")).thenReturn(Optional.empty());

        assertThrows(ResourceNotFoundException.class, () ->
                studentService.updateStudent("12345678-5", dto));
    }

    @Test
    @DisplayName("Should throw BusinessRuleException when updating career to an INACTIVE career")
    void testUpdateStudent_CareerUpdate_Inactive() {
        StudentUpdateDTO dto = StudentUpdateDTO.builder()
                .careerCode("99999")
                .build();

        when(studentRepository.findByRun("12345678-5")).thenReturn(Optional.of(sampleStudent));
        when(careerRepository.findByCode("99999")).thenReturn(Optional.of(careerInactive));

        assertThrows(BusinessRuleException.class, () ->
                studentService.updateStudent("12345678-5", dto));
    }

    @Test
    @DisplayName("Should throw BusinessRuleException when new career has no active plan")
    void testUpdateStudent_CareerUpdate_NoActivePlan() {
        CareerEntity newCareer = CareerEntity.builder()
                .code("10451")
                .name("Técnico en Análisis de Datos")
                .isActive(true)
                .build();

        StudentUpdateDTO dto = StudentUpdateDTO.builder()
                .careerCode("10451")
                .build();

        when(studentRepository.findByRun("12345678-5")).thenReturn(Optional.of(sampleStudent));
        when(careerRepository.findByCode("10451")).thenReturn(Optional.of(newCareer));
        when(studyPlanRepository.findByCareer_CodeAndIsActiveTrue("10451")).thenReturn(Optional.empty());

        assertThrows(BusinessRuleException.class, () ->
                studentService.updateStudent("12345678-5", dto));
    }

    // =========================================================================
    // 4. deleteStudent Tests
    // =========================================================================

    @Test
    @DisplayName("Should successfully delete student without enrollments or history")
    void testDeleteStudent_Success() {
        when(studentRepository.findByRun("12345678-5")).thenReturn(Optional.of(sampleStudent));

        studentService.deleteStudent("12345678-5");

        verify(studentRepository).delete(sampleStudent);
    }

    @Test
    @DisplayName("Should throw ResourceNotFoundException when deleting non-existent student")
    void testDeleteStudent_NotFound() {
        when(studentRepository.findByRun("12345678-5")).thenReturn(Optional.empty());

        assertThrows(ResourceNotFoundException.class, () ->
                studentService.deleteStudent("12345678-5"));
        verify(studentRepository, never()).delete(any());
    }

    // =========================================================================
    // 5. Email Generation and Collision Handling
    // =========================================================================

    @Test
    @DisplayName("Should handle email collision by appending counter suffix")
    void testGenerateUniqueEmail_WithCollision() {
        when(studentRepository.existsByEmail("maria.lopez@sigaipt.cl")).thenReturn(true);
        when(studentRepository.existsByEmail("maria.lopez2@sigaipt.cl")).thenReturn(false);

        String email = studentService.generateUniqueEmail("María José", "López");

        assertEquals("maria.lopez2@sigaipt.cl", email);
    }
}
