package cl.usach.tingeso.service;

import cl.usach.tingeso.dto.TeacherRegistrationDTO;
import cl.usach.tingeso.dto.TeacherResponseDTO;
import cl.usach.tingeso.dto.TeacherUpdateDTO;
import cl.usach.tingeso.entity.AcademicDegree;
import cl.usach.tingeso.entity.TeacherEntity;
import cl.usach.tingeso.exception.BusinessRuleException;
import cl.usach.tingeso.exception.ResourceNotFoundException;
import cl.usach.tingeso.repository.StudentRepository;
import cl.usach.tingeso.repository.TeacherRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Unit tests for TeacherService.
 * Layer: Service.
 * Verifies teacher registration, update, deactivation, deletion, queries, and business rules.
 */
@ExtendWith(MockitoExtension.class)
class TeacherServiceTest {

    @Mock
    private TeacherRepository teacherRepository;

    @Mock
    private StudentRepository studentRepository;

    @Mock
    private InstitutionalEmailService institutionalEmailService;

    @Mock
    private KeycloakUserService keycloakUserService;

    @InjectMocks
    private TeacherService teacherService;

    private TeacherEntity teacher1;

    @BeforeEach
    void setUp() {
        teacher1 = TeacherEntity.builder()
                .run("11111111-1")
                .firstName("Pedro")
                .paternalLastName("González")
                .maternalLastName("Pérez")
                .email("pedro.gonzalez@sigaipt.cl")
                .professionalTitle("Ingeniero Civil en Informática")
                .academicDegree(AcademicDegree.MAGISTER)
                .isActive(true)
                .build();
    }

    @Test
    @DisplayName("Should register teacher successfully with autogenerated email and active status")
    void testRegisterTeacher_Success() {
        TeacherRegistrationDTO dto = TeacherRegistrationDTO.builder()
                .run("11.111.111-1")
                .firstName("Pedro")
                .paternalLastName("González")
                .maternalLastName("Pérez")
                .professionalTitle("Ingeniero Civil en Informática")
                .academicDegree(AcademicDegree.MAGISTER)
                .build();

        when(teacherRepository.existsByRun("11111111-1")).thenReturn(false);
        when(studentRepository.existsByRun("11111111-1")).thenReturn(false);
        when(institutionalEmailService.generateUniqueEmail("Pedro", "González", "Pérez"))
                .thenReturn("pedro.gonzalez@sigaipt.cl");
        when(teacherRepository.save(any(TeacherEntity.class))).thenReturn(teacher1);
        when(keycloakUserService.createTeacherUser(anyString(), anyString(), anyString(), anyString()))
                .thenReturn("keycloak-user-uuid");

        TeacherResponseDTO response = teacherService.registerTeacher(dto);

        assertNotNull(response);
        assertEquals("11111111-1", response.getRun());
        assertEquals("pedro.gonzalez@sigaipt.cl", response.getEmail());
        assertTrue(response.getIsActive());
        assertEquals("Magíster", response.getAcademicDegreeDisplayName());
        verify(keycloakUserService).createTeacherUser("11111111-1", "pedro.gonzalez@sigaipt.cl", "Pedro", "González");
    }

    @Test
    @DisplayName("Should throw exception when registering teacher with invalid RUN")
    void testRegisterTeacher_InvalidRun() {
        TeacherRegistrationDTO dto = TeacherRegistrationDTO.builder()
                .run("12345678-0") // invalid verification digit
                .firstName("Juan")
                .paternalLastName("Perez")
                .maternalLastName("Soto")
                .professionalTitle("Ingeniero")
                .academicDegree(AcademicDegree.LICENCIATURA)
                .build();

        BusinessRuleException ex = assertThrows(BusinessRuleException.class, () -> teacherService.registerTeacher(dto));
        assertTrue(ex.getMessage().contains("invalid"));
        verify(teacherRepository, never()).save(any());
    }

    @Test
    @DisplayName("Should throw exception when teacher RUN already exists in system")
    void testRegisterTeacher_DuplicateRun() {
        TeacherRegistrationDTO dto = TeacherRegistrationDTO.builder()
                .run("11111111-1")
                .firstName("Pedro")
                .paternalLastName("González")
                .maternalLastName("Pérez")
                .professionalTitle("Ingeniero")
                .academicDegree(AcademicDegree.MAGISTER)
                .build();

        when(teacherRepository.existsByRun("11111111-1")).thenReturn(true);

        BusinessRuleException ex = assertThrows(BusinessRuleException.class, () -> teacherService.registerTeacher(dto));
        assertTrue(ex.getMessage().contains("already registered"));
        verify(teacherRepository, never()).save(any());
    }

    @Test
    @DisplayName("Should throw exception when Keycloak user provisioning fails")
    void testRegisterTeacher_KeycloakFailure() {
        TeacherRegistrationDTO dto = TeacherRegistrationDTO.builder()
                .run("11111111-1")
                .firstName("Pedro")
                .paternalLastName("González")
                .maternalLastName("Pérez")
                .professionalTitle("Ingeniero")
                .academicDegree(AcademicDegree.MAGISTER)
                .build();

        when(teacherRepository.existsByRun("11111111-1")).thenReturn(false);
        when(studentRepository.existsByRun("11111111-1")).thenReturn(false);
        when(institutionalEmailService.generateUniqueEmail(any(), any(), any())).thenReturn("pedro.gonzalez@sigaipt.cl");
        when(teacherRepository.save(any(TeacherEntity.class))).thenReturn(teacher1);
        when(keycloakUserService.createTeacherUser(any(), any(), any(), any()))
                .thenThrow(new RuntimeException("Keycloak connection error"));

        BusinessRuleException ex = assertThrows(BusinessRuleException.class, () -> teacherService.registerTeacher(dto));
        assertTrue(ex.getMessage().contains("authentication server"));
    }

    @Test
    @DisplayName("Should update teacher details successfully")
    void testUpdateTeacher_Success() {
        TeacherUpdateDTO dto = TeacherUpdateDTO.builder()
                .firstName("Pedro Antonio")
                .paternalLastName("González")
                .maternalLastName("Pérez")
                .professionalTitle("Doctor en Ciencias de la Computación")
                .academicDegree(AcademicDegree.DOCTORADO)
                .isActive(true)
                .build();

        when(teacherRepository.findByRun("11111111-1")).thenReturn(Optional.of(teacher1));
        when(teacherRepository.save(any(TeacherEntity.class))).thenReturn(teacher1);

        TeacherResponseDTO response = teacherService.updateTeacher("11111111-1", dto);

        assertNotNull(response);
        assertEquals("Pedro Antonio", teacher1.getFirstName());
        assertEquals(AcademicDegree.DOCTORADO, teacher1.getAcademicDegree());
    }

    @Test
    @DisplayName("Should throw exception when updating non-existent teacher")
    void testUpdateTeacher_NotFound() {
        TeacherUpdateDTO dto = TeacherUpdateDTO.builder()
                .firstName("Juan")
                .paternalLastName("Perez")
                .maternalLastName("Soto")
                .professionalTitle("Ingeniero")
                .academicDegree(AcademicDegree.LICENCIATURA)
                .isActive(true)
                .build();

        when(teacherRepository.findByRun("99999999-9")).thenReturn(Optional.empty());

        assertThrows(ResourceNotFoundException.class, () -> teacherService.updateTeacher("99999999-9", dto));
    }

    @Test
    @DisplayName("Should delete teacher successfully when no associated sections exist")
    void testDeleteTeacher_Success() {
        when(teacherRepository.findByRun("11111111-1")).thenReturn(Optional.of(teacher1));

        teacherService.deleteTeacher("11111111-1");

        verify(teacherRepository).delete(teacher1);
    }

    @Test
    @DisplayName("Should get teacher by RUN successfully")
    void testGetTeacherByRun_Success() {
        when(teacherRepository.findByRun("11111111-1")).thenReturn(Optional.of(teacher1));

        TeacherResponseDTO response = teacherService.getTeacherByRun("11111111-1");

        assertNotNull(response);
        assertEquals("11111111-1", response.getRun());
        assertEquals("pedro.gonzalez@sigaipt.cl", response.getEmail());
    }

    @Test
    @DisplayName("Should get all teachers with active and search filter")
    void testGetAllTeachers_WithFilters() {
        when(teacherRepository.findByIsActiveOrderByPaternalLastNameAscFirstNameAsc(true))
                .thenReturn(List.of(teacher1));

        List<TeacherResponseDTO> result = teacherService.getAllTeachers(true, "pedro");

        assertEquals(1, result.size());
        assertEquals("11111111-1", result.get(0).getRun());
    }
}
