package cl.usach.tingeso.service;

import cl.usach.tingeso.exception.BusinessRuleException;
import cl.usach.tingeso.exception.ResourceNotFoundException;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.RestClient;

import java.net.URI;
import java.util.Collections;
import java.util.List;
import java.util.Map;

/**
 * KeycloakUserService interacts with Keycloak Admin REST API to provision
 * and manage user accounts, credentials, and roles for SIGA IPT.
 * Layer: Service.
 */
@Service
@Slf4j
public class KeycloakUserService {

    private final RestClient restClient;
    private final String serverUrl;
    private final String realm;
    private final String clientId;
    private final String clientSecret;
    private final String defaultPassword;

    public KeycloakUserService(
            RestClient.Builder restClientBuilder,
            @Value("${keycloak.server-url:http://localhost:8080}") String serverUrl,
            @Value("${keycloak.realm:siga-ipt-realm}") String realm,
            @Value("${keycloak.client-id:siga-backend-service}") String clientId,
            @Value("${keycloak.client-secret}") String clientSecret,
            @Value("${keycloak.default-password:Siga2026!}") String defaultPassword
    ) {
        this.restClient = restClientBuilder.build();
        this.serverUrl = serverUrl.replaceAll("/$", "");
        this.realm = realm;
        this.clientId = clientId;
        this.clientSecret = clientSecret;
        this.defaultPassword = defaultPassword;
    }

    /**
     * Obtains a service account access token using client_credentials grant.
     *
     * @return bearer token string
     */
    public String getServiceAccountToken() {
        String tokenUrl = String.format("%s/realms/%s/protocol/openid-connect/token", serverUrl, realm);

        MultiValueMap<String, String> formData = new LinkedMultiValueMap<>();
        formData.add("grant_type", "client_credentials");
        formData.add("client_id", clientId);
        formData.add("client_secret", clientSecret);

        try {
            Map<String, Object> response = restClient.post()
                    .uri(tokenUrl)
                    .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                    .body(formData)
                    .retrieve()
                    .body(new ParameterizedTypeReference<Map<String, Object>>() {});

            if (response != null && response.containsKey("access_token")) {
                return (String) response.get("access_token");
            }
            throw new BusinessRuleException("Failed to retrieve access token from Keycloak: response missing access_token");
        } catch (Exception e) {
            log.error("Error retrieving Keycloak service account token: {}", e.getMessage());
            throw new BusinessRuleException("Failed to authenticate with Keycloak service account: " + e.getMessage());
        }
    }

    /**
     * Provisions a new student user in Keycloak with temporary default password and STUDENT realm role.
     *
     * @param run student national ID (used as Keycloak username)
     * @param email autogenerated student institutional email
     * @param firstName student first name
     * @param lastName student paternal last name
     * @return generated Keycloak user UUID
     */
    public String createStudentUser(String run, String email, String firstName, String lastName) {
        String adminToken = getServiceAccountToken();
        String usersUrl = String.format("%s/admin/realms/%s/users", serverUrl, realm);

        Map<String, Object> userPayload = Map.of(
                "username", run,
                "email", email,
                "firstName", firstName,
                "lastName", lastName,
                "enabled", true,
                "emailVerified", true,
                "credentials", List.of(
                        Map.of(
                                "type", "password",
                                "value", defaultPassword,
                                "temporary", true
                        )
                )
        );

        String userId;
        try {
            ResponseEntity<Void> response = restClient.post()
                    .uri(usersUrl)
                    .header(HttpHeaders.AUTHORIZATION, "Bearer " + adminToken)
                    .contentType(MediaType.APPLICATION_JSON)
                    .body(userPayload)
                    .retrieve()
                    .toBodilessEntity();

            URI location = response.getHeaders().getLocation();
            if (location != null) {
                String path = location.getPath();
                userId = path.substring(path.lastIndexOf('/') + 1);
            } else {
                userId = findUserIdByUsername(run, adminToken);
            }
        } catch (HttpClientErrorException.Conflict conflictEx) {
            log.warn("Keycloak user conflict for RUN {}: {}", run, conflictEx.getMessage());
            throw new BusinessRuleException("A user with this RUN or email already exists in Keycloak: " + run);
        } catch (Exception e) {
            log.error("Error creating student user in Keycloak: {}", e.getMessage());
            throw new BusinessRuleException("Failed to provision student in Keycloak: " + e.getMessage());
        }

        // Assign STUDENT realm role
        assignRealmRole(userId, "STUDENT", adminToken);
        log.info("Student {} successfully provisioned in Keycloak with ID: {} and temporary password", run, userId);
        return userId;
    }

    /**
     * Resets or changes a user's password in Keycloak.
     *
     * @param username user username or RUN
     * @param newPassword new password string
     * @param temporary whether the user must change password at next login
     */
    public void resetPassword(String username, String newPassword, boolean temporary) {
        String adminToken = getServiceAccountToken();
        String userId = findUserIdByUsername(username, adminToken);
        if (userId == null) {
            throw new ResourceNotFoundException("User not found in Keycloak with username: " + username);
        }

        String resetPasswordUrl = String.format("%s/admin/realms/%s/users/%s/reset-password", serverUrl, realm, userId);
        Map<String, Object> passwordPayload = Map.of(
                "type", "password",
                "value", newPassword,
                "temporary", temporary
        );

        try {
            restClient.put()
                    .uri(resetPasswordUrl)
                    .header(HttpHeaders.AUTHORIZATION, "Bearer " + adminToken)
                    .contentType(MediaType.APPLICATION_JSON)
                    .body(passwordPayload)
                    .retrieve()
                    .toBodilessEntity();
            log.info("Password successfully updated in Keycloak for user: {}", username);
        } catch (Exception e) {
            log.error("Failed to reset password for user {}: {}", username, e.getMessage());
            throw new BusinessRuleException("Failed to update password in Keycloak: " + e.getMessage());
        }
    }

    /**
     * Deletes a user from Keycloak by RUN if they exist.
     *
     * @param run student RUN
     */
    public void deleteUser(String run) {
        try {
            String adminToken = getServiceAccountToken();
            String userId = findUserIdByUsername(run, adminToken);
            if (userId != null) {
                String deleteUrl = String.format("%s/admin/realms/%s/users/%s", serverUrl, realm, userId);
                restClient.delete()
                        .uri(deleteUrl)
                        .header(HttpHeaders.AUTHORIZATION, "Bearer " + adminToken)
                        .retrieve()
                        .toBodilessEntity();
                log.info("Deleted user {} from Keycloak (ID: {})", run, userId);
            }
        } catch (Exception e) {
            log.warn("Could not delete user {} from Keycloak: {}", run, e.getMessage());
        }
    }

    /**
     * Finds a Keycloak user UUID by username (RUN).
     */
    private String findUserIdByUsername(String username, String adminToken) {
        String searchUrl = String.format("%s/admin/realms/%s/users?username=%s&exact=true", serverUrl, realm, username);
        try {
            List<Map<String, Object>> users = restClient.get()
                    .uri(searchUrl)
                    .header(HttpHeaders.AUTHORIZATION, "Bearer " + adminToken)
                    .retrieve()
                    .body(new ParameterizedTypeReference<List<Map<String, Object>>>() {});

            if (users != null && !users.isEmpty()) {
                return (String) users.get(0).get("id");
            }
        } catch (Exception e) {
            log.warn("Failed searching user ID for {}: {}", username, e.getMessage());
        }
        return null;
    }

    /**
     * Assigns a realm role to a Keycloak user.
     */
    private void assignRealmRole(String userId, String roleName, String adminToken) {
        try {
            String roleUrl = String.format("%s/admin/realms/%s/roles/%s", serverUrl, realm, roleName);
            Map<String, Object> roleRepresentation = restClient.get()
                    .uri(roleUrl)
                    .header(HttpHeaders.AUTHORIZATION, "Bearer " + adminToken)
                    .retrieve()
                    .body(new ParameterizedTypeReference<Map<String, Object>>() {});

            if (roleRepresentation != null) {
                String roleMappingUrl = String.format("%s/admin/realms/%s/users/%s/role-mappings/realm", serverUrl, realm, userId);
                restClient.post()
                        .uri(roleMappingUrl)
                        .header(HttpHeaders.AUTHORIZATION, "Bearer " + adminToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .body(Collections.singletonList(roleRepresentation))
                        .retrieve()
                        .toBodilessEntity();
                log.debug("Role {} successfully assigned to Keycloak user {}", roleName, userId);
            }
        } catch (Exception e) {
            log.error("Failed to assign role {} to user {}: {}", roleName, userId, e.getMessage());
            throw new BusinessRuleException("User created but failed to assign role in Keycloak: " + e.getMessage());
        }
    }
}
