package cl.usach.tingeso.service;

import cl.usach.tingeso.dto.StudentRegistrationDTO;
import cl.usach.tingeso.dto.StudentResponseDTO;
import cl.usach.tingeso.dto.StudentUpdateDTO;
import cl.usach.tingeso.entity.AcademicStatus;
import cl.usach.tingeso.entity.CareerEntity;
import cl.usach.tingeso.entity.StudentEntity;
import cl.usach.tingeso.entity.StudyPlanEntity;
import cl.usach.tingeso.exception.BusinessRuleException;
import cl.usach.tingeso.exception.ResourceNotFoundException;
import cl.usach.tingeso.repository.CareerRepository;
import cl.usach.tingeso.repository.StudentRepository;
import cl.usach.tingeso.repository.StudyPlanRepository;
import cl.usach.tingeso.util.RunValidatorUtil;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.text.Normalizer;
import java.util.List;

/**
 * StudentService implements all business logic for student management.
 * Corresponds to Epic 1: Student Management.
 * Layer: Service.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class StudentService {

    private final StudentRepository studentRepository;
    private final CareerRepository careerRepository;
    private final StudyPlanRepository studyPlanRepository;
    private final KeycloakUserService keycloakUserService;

    /**
     * Registers a new student in the institution.
     * Enforces the following business rules:
     * - RUN must be valid according to Chilean Modulo 11 and unique.
     * - Career must exist and be ACTIVE.
     * - Student is automatically assigned the active study plan for that career.
     * - Institutional email is autogenerated with format name.paternallastname@sigaipt.cl.
     * - Initial academic status is automatically REGULAR.
     * - Student is provisioned in Keycloak with temporary password and STUDENT role.
     *
     * @param dto the registration payload
     * @return the created student response DTO
     */
    @Transactional
    public StudentResponseDTO registerStudent(StudentRegistrationDTO dto) {
        log.info("Attempting to register student with RUN: {}", dto.getRun());

        String cleanedRun = RunValidatorUtil.cleanFormat(dto.getRun());
        if (!RunValidatorUtil.isValid(cleanedRun)) {
            throw new BusinessRuleException("The provided RUN is invalid: " + dto.getRun());
        }

        if (studentRepository.existsByRun(cleanedRun)) {
            throw new BusinessRuleException("A student with RUN " + cleanedRun + " is already registered.");
        }

        CareerEntity career = careerRepository.findByCode(dto.getCareerCode())
                .orElseThrow(() -> new ResourceNotFoundException("Career not found with code: " + dto.getCareerCode()));

        if (Boolean.FALSE.equals(career.getIsActive())) {
            throw new BusinessRuleException("Cannot enroll student in an INACTIVE career: " + career.getName());
        }

        StudyPlanEntity activePlan = studyPlanRepository.findByCareer_CodeAndIsActiveTrue(career.getCode())
                .orElseThrow(() -> new BusinessRuleException("No active study plan found for career: " + career.getCode()));

        String autogeneratedEmail = generateUniqueEmail(dto.getFirstName(), dto.getPaternalLastName());

        StudentEntity student = StudentEntity.builder()
                .run(cleanedRun)
                .firstName(dto.getFirstName().trim())
                .paternalLastName(dto.getPaternalLastName().trim())
                .maternalLastName(dto.getMaternalLastName().trim())
                .email(autogeneratedEmail)
                .career(career)
                .studyPlan(activePlan)
                .academicStatus(AcademicStatus.REGULAR)
                .build();

        StudentEntity saved = studentRepository.save(student);
        log.info("Student successfully registered: {} with email: {}", saved.getRun(), saved.getEmail());

        // Provision user in Keycloak with temporary default password and STUDENT role
        keycloakUserService.createStudentUser(saved.getRun(), saved.getEmail(), saved.getFirstName(), saved.getPaternalLastName());

        return mapToResponseDTO(saved);
    }

    /**
     * Retrieves all registered students.
     *
     * @return list of student response DTOs
     */
    @Transactional(readOnly = true)
    public List<StudentResponseDTO> getAllStudents() {
        return studentRepository.findAll().stream()
                .map(this::mapToResponseDTO)
                .toList();
    }

    /**
     * Retrieves a student by their unique RUN.
     *
     * @param run RUN of the student
     * @return the student response DTO
     */
    @Transactional(readOnly = true)
    public StudentResponseDTO getStudentByRun(String run) {
        String cleaned = RunValidatorUtil.cleanFormat(run);
        StudentEntity student = studentRepository.findByRun(cleaned)
                .orElseThrow(() -> new ResourceNotFoundException("Student not found with RUN: " + cleaned));
        return mapToResponseDTO(student);
    }

    /**
     * Updates student information enforcing business rules:
     * - EGRESADO and ELIMINADO cannot be manually assigned by any user.
     * - AcademicStatus can only be modified to REGULAR, POSTERGACION, or RETIRO_TEMPORAL.
     * - Career and Study Plan can only be changed if the student has no enrollments or academic history.
     *
     * @param run student RUN
     * @param dto update payload
     * @return updated student response DTO
     */
    @Transactional
    public StudentResponseDTO updateStudent(String run, StudentUpdateDTO dto) {
        String cleaned = RunValidatorUtil.cleanFormat(run);
        StudentEntity student = studentRepository.findByRun(cleaned)
                .orElseThrow(() -> new ResourceNotFoundException("Student not found with RUN: " + cleaned));

        if (dto.getAcademicStatus() != null) {
            if (dto.getAcademicStatus() == AcademicStatus.EGRESADO || dto.getAcademicStatus() == AcademicStatus.ELIMINADO) {
                throw new BusinessRuleException("The states EGRESADO and ELIMINADO cannot be assigned manually.");
            }
            student.setAcademicStatus(dto.getAcademicStatus());
        }

        if (dto.getFirstName() != null && !dto.getFirstName().isBlank()) {
            student.setFirstName(dto.getFirstName().trim());
        }
        if (dto.getPaternalLastName() != null && !dto.getPaternalLastName().isBlank()) {
            student.setPaternalLastName(dto.getPaternalLastName().trim());
        }
        if (dto.getMaternalLastName() != null && !dto.getMaternalLastName().isBlank()) {
            student.setMaternalLastName(dto.getMaternalLastName().trim());
        }

        if (dto.getCareerCode() != null && !dto.getCareerCode().equals(student.getCareer().getCode())) {
            if (hasEnrollmentsOrAcademicHistory(student)) {
                throw new BusinessRuleException("Career and study plan cannot be modified because the student has enrollments or academic history.");
            }

            CareerEntity newCareer = careerRepository.findByCode(dto.getCareerCode())
                    .orElseThrow(() -> new ResourceNotFoundException("Career not found with code: " + dto.getCareerCode()));

            if (Boolean.FALSE.equals(newCareer.getIsActive())) {
                throw new BusinessRuleException("Cannot transfer student to an INACTIVE career: " + newCareer.getName());
            }

            StudyPlanEntity newActivePlan = studyPlanRepository.findByCareer_CodeAndIsActiveTrue(newCareer.getCode())
                    .orElseThrow(() -> new BusinessRuleException("No active study plan found for career: " + newCareer.getCode()));

            student.setCareer(newCareer);
            student.setStudyPlan(newActivePlan);
        }

        StudentEntity updated = studentRepository.save(student);
        log.info("Student updated successfully: {}", updated.getRun());
        return mapToResponseDTO(updated);
    }

    /**
     * Deletes a student physically from the system.
     * Enforces the rule: students with enrollments or academic history CANNOT be deleted physically.
     *
     * @param run RUN of the student to delete
     */
    @Transactional
    public void deleteStudent(String run) {
        String cleaned = RunValidatorUtil.cleanFormat(run);
        StudentEntity student = studentRepository.findByRun(cleaned)
                .orElseThrow(() -> new ResourceNotFoundException("Student not found with RUN: " + cleaned));

        if (hasEnrollmentsOrAcademicHistory(student)) {
            throw new BusinessRuleException("Students with course enrollments or academic history cannot be physically deleted.");
        }

        studentRepository.delete(student);
        keycloakUserService.deleteUser(cleaned);
        log.info("Student physically deleted: {}", cleaned);
    }

    /**
     * Checks if the student has enrollments or academic history.
     * In Epic 1, this returns false until enrollment and grade history tables are implemented.
     *
     * @param student student entity
     * @return true if enrollments or history exist
     */
    public boolean hasEnrollmentsOrAcademicHistory(StudentEntity student) {
        // Will be connected to EnrollmentRepository in Epics 6 & 7
        return false;
    }

    /**
     * Autogenerates a unique institutional email: firstName.paternalLastName@sigaipt.cl.
     * Removes accents, special characters, and handles duplicates.
     *
     * @param firstName first name
     * @param paternalLastName paternal last name
     * @return unique institutional email
     */
    public String generateUniqueEmail(String firstName, String paternalLastName) {
        String sanitizedFirst = sanitizeForEmail(firstName.split(" ")[0]);
        String sanitizedLast = sanitizeForEmail(paternalLastName);

        String baseEmail = (sanitizedFirst + "." + sanitizedLast + "@sigaipt.cl").toLowerCase();
        String candidate = baseEmail;
        int counter = 2;

        while (studentRepository.existsByEmail(candidate)) {
            candidate = (sanitizedFirst + "." + sanitizedLast + counter + "@sigaipt.cl").toLowerCase();
            counter++;
        }

        return candidate;
    }

    private String sanitizeForEmail(String input) {
        if (input == null) return "";
        String normalized = Normalizer.normalize(input.trim(), Normalizer.Form.NFD);
        return normalized.replaceAll("[\\p{InCombiningDiacriticalMarks}]", "")
                .replaceAll("[^a-zA-Z0-9]", "");
    }

    /**
     * Maps StudentEntity to StudentResponseDTO, formatting full name.
     */
    public StudentResponseDTO mapToResponseDTO(StudentEntity entity) {
        String fullName = String.format("%s %s %s",
                entity.getFirstName() != null ? entity.getFirstName().trim() : "",
                entity.getPaternalLastName() != null ? entity.getPaternalLastName().trim() : "",
                entity.getMaternalLastName() != null ? entity.getMaternalLastName().trim() : "").trim();

        return StudentResponseDTO.builder()
                .run(entity.getRun())
                .firstName(entity.getFirstName())
                .paternalLastName(entity.getPaternalLastName())
                .maternalLastName(entity.getMaternalLastName())
                .fullName(fullName)
                .email(entity.getEmail())
                .academicStatus(entity.getAcademicStatus())
                .careerCode(entity.getCareer() != null ? entity.getCareer().getCode() : null)
                .careerName(entity.getCareer() != null ? entity.getCareer().getName() : null)
                .studyPlanId(entity.getStudyPlan() != null ? entity.getStudyPlan().getId() : null)
                .studyPlanCode(entity.getStudyPlan() != null ? entity.getStudyPlan().getCode() : null)
                .build();
    }
}
