package cl.usach.tingeso.service;

import cl.usach.tingeso.dto.TeacherRegistrationDTO;
import cl.usach.tingeso.dto.TeacherResponseDTO;
import cl.usach.tingeso.dto.TeacherUpdateDTO;
import cl.usach.tingeso.entity.TeacherEntity;
import cl.usach.tingeso.exception.BusinessRuleException;
import cl.usach.tingeso.exception.ResourceNotFoundException;
import cl.usach.tingeso.repository.StudentRepository;
import cl.usach.tingeso.repository.TeacherRepository;
import cl.usach.tingeso.util.RunValidatorUtil;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * TeacherService implements all business logic and validations for faculty/teacher management.
 * Corresponds to Epic 4: Teacher Management.
 * Layer: Service.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class TeacherService {

    private final TeacherRepository teacherRepository;
    private final StudentRepository studentRepository;
    private final InstitutionalEmailService institutionalEmailService;
    private final KeycloakUserService keycloakUserService;

    /**
     * Registers a new teacher in the institution.
     * Enforces the following business rules:
     * - RUN must be valid according to Chilean Modulo 11 and unique.
     * - Institutional email is autogenerated ensuring no collisions across students and teachers.
     * - Initial status is automatically initialized to true (ACTIVO).
     * - Teacher is provisioned in Keycloak with TEACHER realm role and temporary password.
     *
     * @param dto registration payload
     * @return created teacher response DTO
     */
    @Transactional
    public TeacherResponseDTO registerTeacher(TeacherRegistrationDTO dto) {
        log.info("Attempting to register teacher with RUN: {}", dto.getRun());

        String cleanedRun = RunValidatorUtil.cleanFormat(dto.getRun());
        if (!RunValidatorUtil.isValid(cleanedRun)) {
            throw new BusinessRuleException("The provided RUN is invalid: " + dto.getRun());
        }

        if (teacherRepository.existsByRun(cleanedRun) || studentRepository.existsByRun(cleanedRun)) {
            throw new BusinessRuleException("A user with RUN " + cleanedRun + " is already registered.");
        }

        String email = institutionalEmailService.generateUniqueEmail(
                dto.getFirstName(), dto.getPaternalLastName(), dto.getMaternalLastName());

        TeacherEntity teacher = TeacherEntity.builder()
                .run(cleanedRun)
                .firstName(dto.getFirstName().trim())
                .paternalLastName(dto.getPaternalLastName().trim())
                .maternalLastName(dto.getMaternalLastName().trim())
                .email(email)
                .professionalTitle(dto.getProfessionalTitle().trim())
                .academicDegree(dto.getAcademicDegree())
                .isActive(true)
                .build();

        TeacherEntity savedTeacher = teacherRepository.save(teacher);
        log.info("Teacher {} registered successfully in database with email: {}", cleanedRun, email);

        // Provision Keycloak user
        try {
            keycloakUserService.createTeacherUser(
                    cleanedRun,
                    email,
                    savedTeacher.getFirstName(),
                    savedTeacher.getPaternalLastName()
            );
        } catch (Exception e) {
            log.error("Failed to provision teacher in Keycloak for RUN {}: {}", cleanedRun, e.getMessage());
            throw new BusinessRuleException("Failed to provision teacher in authentication server: " + e.getMessage());
        }

        return mapToResponseDTO(savedTeacher);
    }

    /**
     * Updates teacher details.
     * Enforces that a teacher cannot be deactivated if they have assigned sections in an OPEN period.
     * Does not alter historical section records.
     *
     * @param run teacher RUN
     * @param dto update payload
     * @return updated teacher response DTO
     */
    @Transactional
    public TeacherResponseDTO updateTeacher(String run, TeacherUpdateDTO dto) {
        String cleanedRun = RunValidatorUtil.cleanFormat(run);
        TeacherEntity teacher = teacherRepository.findByRun(cleanedRun)
                .orElseThrow(() -> new ResourceNotFoundException("Teacher not found with RUN: " + run));

        // If transitioning from ACTIVE to INACTIVE, verify no open sections exist
        if (Boolean.TRUE.equals(teacher.getIsActive()) && Boolean.FALSE.equals(dto.getIsActive())) {
            if (hasOpenSections(cleanedRun)) {
                throw new BusinessRuleException("Cannot deactivate teacher while they have assigned sections in an OPEN academic period.");
            }
        }

        teacher.setFirstName(dto.getFirstName().trim());
        teacher.setPaternalLastName(dto.getPaternalLastName().trim());
        teacher.setMaternalLastName(dto.getMaternalLastName().trim());
        teacher.setProfessionalTitle(dto.getProfessionalTitle().trim());
        teacher.setAcademicDegree(dto.getAcademicDegree());
        teacher.setIsActive(dto.getIsActive());

        TeacherEntity updatedTeacher = teacherRepository.save(teacher);
        log.info("Teacher {} updated successfully. Active status: {}", cleanedRun, updatedTeacher.getIsActive());

        return mapToResponseDTO(updatedTeacher);
    }

    /**
     * Deletes a teacher physically only if they have no associated sections.
     *
     * @param run teacher RUN
     */
    @Transactional
    public void deleteTeacher(String run) {
        String cleanedRun = RunValidatorUtil.cleanFormat(run);
        TeacherEntity teacher = teacherRepository.findByRun(cleanedRun)
                .orElseThrow(() -> new ResourceNotFoundException("Teacher not found with RUN: " + run));

        if (hasAssociatedSections(cleanedRun)) {
            throw new BusinessRuleException("A teacher with associated course sections cannot be physically deleted from the system.");
        }

        teacherRepository.delete(teacher);
        log.info("Teacher {} deleted successfully", cleanedRun);
    }

    /**
     * Retrieves teacher details by RUN.
     *
     * @param run teacher RUN
     * @return teacher response DTO
     */
    public TeacherResponseDTO getTeacherByRun(String run) {
        String cleanedRun = RunValidatorUtil.cleanFormat(run);
        TeacherEntity teacher = teacherRepository.findByRun(cleanedRun)
                .orElseThrow(() -> new ResourceNotFoundException("Teacher not found with RUN: " + run));
        return mapToResponseDTO(teacher);
    }

    /**
     * Retrieves all teachers with optional status and search filtering.
     *
     * @param active optional filter by active status
     * @param search optional search query (matches RUN, first name or last names)
     * @return list of teacher response DTOs
     */
    public List<TeacherResponseDTO> getAllTeachers(Boolean active, String search) {
        List<TeacherEntity> teachers;

        if (active != null) {
            teachers = teacherRepository.findByIsActiveOrderByPaternalLastNameAscFirstNameAsc(active);
        } else {
            teachers = teacherRepository.findAllByOrderByPaternalLastNameAscFirstNameAsc();
        }

        if (search != null && !search.trim().isEmpty()) {
            String lowerSearch = search.trim().toLowerCase();
            teachers = teachers.stream()
                    .filter(t -> t.getRun().toLowerCase().contains(lowerSearch)
                            || t.getFullName().toLowerCase().contains(lowerSearch)
                            || t.getEmail().toLowerCase().contains(lowerSearch)
                            || t.getProfessionalTitle().toLowerCase().contains(lowerSearch))
                    .toList();
        }

        return teachers.stream().map(this::mapToResponseDTO).toList();
    }

    /**
     * Checks if the teacher is assigned to any sections in an OPEN period.
     * Prepared for Epic 5 integration.
     *
     * @param run teacher RUN
     * @return true if has open sections, false otherwise
     */
    public boolean hasOpenSections(String run) {
        // In Epic 5, this will delegate to sectionRepository.countByTeacher_RunAndPeriod_Status(run, PeriodStatus.ABIERTO) > 0
        return false;
    }

    /**
     * Checks if the teacher has any associated course sections (active or historical).
     * Prepared for Epic 5 integration.
     *
     * @param run teacher RUN
     * @return true if has associated sections, false otherwise
     */
    public boolean hasAssociatedSections(String run) {
        // In Epic 5, this will delegate to sectionRepository.countByTeacher_Run(run) > 0
        return false;
    }

    /**
     * Converts TeacherEntity to TeacherResponseDTO.
     */
    public TeacherResponseDTO mapToResponseDTO(TeacherEntity teacher) {
        return TeacherResponseDTO.builder()
                .run(teacher.getRun())
                .firstName(teacher.getFirstName())
                .paternalLastName(teacher.getPaternalLastName())
                .maternalLastName(teacher.getMaternalLastName())
                .fullName(teacher.getFullName())
                .email(teacher.getEmail())
                .professionalTitle(teacher.getProfessionalTitle())
                .academicDegree(teacher.getAcademicDegree())
                .academicDegreeDisplayName(teacher.getAcademicDegree() != null ? teacher.getAcademicDegree().getDisplayName() : null)
                .isActive(teacher.getIsActive())
                .build();
    }
}
