package cl.usach.tingeso.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * StudentRegistrationDTO represents the request payload to register a new student.
 * Corresponds to Epic 1: Student Registration.
 * Email is autogenerated by the system and the active study plan is assigned automatically.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class StudentRegistrationDTO {

    /**
     * Chilean National ID (RUN) with clean format and hyphen (e.g., "12345678-9").
     */
    @NotBlank(message = "RUN is required")
    @Pattern(regexp = "^[0-9]{7,8}-[0-9kK]$", message = "RUN must follow the format 12345678-9")
    private String run;

    /**
     * First and middle names of the student.
     */
    @NotBlank(message = "First name is required")
    @Size(max = 100, message = "First name cannot exceed 100 characters")
    private String firstName;

    /**
     * Paternal last name of the student.
     */
    @NotBlank(message = "Paternal last name is required")
    @Size(max = 100, message = "Paternal last name cannot exceed 100 characters")
    private String paternalLastName;

    /**
     * Maternal last name of the student.
     */
    @NotBlank(message = "Maternal last name is required")
    @Size(max = 100, message = "Maternal last name cannot exceed 100 characters")
    private String maternalLastName;

    /**
     * Unique code of the career in which the student will be enrolled (e.g., "10450").
     */
    @NotBlank(message = "Career code is required")
    private String careerCode;
}
